/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {

    // Microsphere Java BOM
    implementation(platform(libs.microsphere.java.dependencies))

    // Jakarta EE BOM
    implementation(platform(libs.jakartaee.bom))

    // Microsphere Java Core
    implementation("io.github.microsphere-projects:microsphere-java-core")

    // Jakarta Servlet
    compileOnly("jakarta.servlet:jakarta.servlet-api")

    // Testing
    testImplementation(libs.junit.jupiter.engine)

    testImplementation(libs.testcontainers)

    testImplementation(libs.testcontainers.junit.jupiter)

    testImplementation(libs.logback.classic)

}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(listOf("-source", "8", "-target", "8"))
}
