[versions]
microsphere-java-dependencies-version = "0.0.6"
jakartaee-version = "9.0.0"
junit-platform-launcher-version = "1.10.2"
junit-jupiter-engine-version = "5.10.2"
testcontainers-version = "1.20.1"
logback-version = "1.3.14"

[libraries]
microsphere-java-dependencies = { group = "io.github.microsphere-projects", name = "microsphere-java-dependencies", version.ref = "microsphere-java-dependencies-version" }
jakartaee-bom = { group = "jakarta.platform", name = "jakarta.jakartaee-bom", version.ref = "jakartaee-version" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform-launcher-version" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter-engine-version" }
testcontainers = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers-version" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers-version" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-version" }

[plugins]
